[workspace]
members = [
    "zircon-object",
    "zircon-loader",
    "linux-object",
    "zircon-syscall",    
    "linux-loader",
    "kernel-hal-unix",
    "kernel-hal",
]

exclude = [
    "zircon-user",
    "zCore",
    "rboot",
    "linux-syscall",
    "kernel-hal-bare",    
]
