[workspace]
members = [
    "drivers",
    "kernel-hal",
    "zircon-object",
    "zircon-syscall",
    "linux-object",
    "linux-syscall",
    "loader",
    "zCore",
]

exclude = [
    "zircon-user",
    "rboot",
]

[profile.release]
lto = true

[patch.'https://github.com/DeathWish5/kernel-sync']
lock = { path = "../../ASYNC/kernel-sync" }

[patch.'https://github.com/rcore-os/executor.git']
executor = { path = "../../ASYNC/PreemptiveScheduler" }