[package]
name = "kernel-hal"
version = "0.1.0"
authors = ["Runji Wang <wangrunji0408@163.com>", "Yuekai Jia <equation618@gmail.com>"]
edition = "2018"
description = "Kernel HAL interface definations."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
libos = ["async-std", "zcore-drivers/mock"]
graphic = ["zcore-drivers/graphic"]

[dependencies]
log = "0.4"
bitflags = "1.3"
trapframe = "0.8.0"
numeric-enum-macro = "0.2"
spin = "0.9"
git-version = "0.3"
cfg-if = "1.0"
zcore-drivers = { path = "../drivers", features = ["virtio"] }

# LibOS mode
[target.'cfg(not(target_os = "none"))'.dependencies]
libc = "0.2"
tempfile = "3"
lazy_static = "1.4"
async-std = { version = "1.10", optional = true }

# Bare-metal mode
[target.'cfg(target_os = "none")'.dependencies]
executor = { git = "https://github.com/rcore-os/executor.git", rev = "a2d02ee9" }
naive-timer = "0.2.0"
lazy_static = { version = "1.4", features = ["spin_no_std"] }
bitmap-allocator = { git = "https://github.com/rcore-os/bitmap-allocator", rev = "b3f9f51" }

# Bare-metal mode on x86_64
[target.'cfg(all(target_os = "none", target_arch = "x86_64"))'.dependencies]
x86_64 = "0.14"
raw-cpuid = "9.0"
x86-smpboot = { git = "https://github.com/rcore-os/x86-smpboot", rev = "43ffedf" }

# Bare-metal mode on riscv64
[target.'cfg(all(target_os = "none", target_arch = "riscv64"))'.dependencies]
riscv = { version = "0.7", features = ["inline-asm"] }
