[package]
name = "kernel-hal"
version = "0.1.0"
authors = ["Runji Wang <wangrunji0408@163.com>", "Yuekai Jia <equation618@gmail.com>"]
edition = "2018"
description = "Kernel HAL interface definations."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
libos = ["async-std"]
board_qemu = []
board_d1 = []

[dependencies]
log = "0.4"
bitflags = "1.2"
trapframe = "0.8.0"
numeric-enum-macro = "0.2"
spin = "0.7"
git-version = "0.3"
cfg-if = "1.0"
acpi = "1.1"

# LibOS mode
[target.'cfg(not(target_os = "none"))'.dependencies]
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"], rev = "0074cbc" }
libc = "0.2"
tempfile = "3"
lazy_static = "1.4"
async-std = { version = "1.9", optional = true }

# Bare-metal mode
[target.'cfg(target_os = "none")'.dependencies]
executor = { git = "https://github.com/rcore-os/executor.git", rev = "a2d02ee9" }
naive-timer = "0.1.0"
lazy_static = { version = "1.4", features = ["spin_no_std"] }
bitmap-allocator = { git = "https://github.com/rcore-os/bitmap-allocator", rev = "b3f9f51" }
# rcore-fs = { git = "https://github.com/rcore-os/rcore-fs", rev = "6df6cd2" }
# device_tree = { git = "https://github.com/rcore-os/device_tree-rs" }
# virtio-drivers = { git = "https://github.com/rcore-os/virtio-drivers", rev = "568276" }

# Bare-metal mode on x86_64
[target.'cfg(all(target_os = "none", target_arch = "x86_64"))'.dependencies]
x86_64 = "0.14"
uart_16550 = "=0.2.15"
raw-cpuid = "9.0"
apic = { git = "https://github.com/rcore-os/apic-rs", rev = "fb86bd7" }
x86-smpboot = { git = "https://github.com/rcore-os/x86-smpboot", rev = "43ffedf" }
# pc-keyboard = "0.5"
# rcore-console = { git = "https://github.com/rcore-os/rcore-console", default-features = false, rev = "a980897b" }
# ps2-mouse = { git = "https://github.com/YXL76/ps2-mouse", branch = "feat" }

# Bare-metal mode on riscv64
[target.'cfg(all(target_os = "none", target_arch = "riscv64"))'.dependencies]
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"], rev = "0074cbc" }
