[package]
name = "linux-loader"
version = "0.1.0"
authors = ["Runji Wang <wangrunji0408@163.com>"]
edition = "2018"
description = "Linux programs loader and runner."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.7"
xmas-elf = "0.7"
structopt = { version = "0.3", default-features = false }
linux-syscall = { path = "../linux-syscall" }
zircon-object = { path = "../zircon-object" }
zircon-hal-unix = { path = "../zircon-hal-unix" }
