name: deploy CI

on:
  push:
  pull_request:

jobs:
  doc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build docs
        run: |
          cargo doc --no-deps --all-features
          cat >target/doc/index.html <<EOF
          <html>
            <head>
              <noscript><meta http-equiv="refresh" content="0; url=kernel_hal/index.html"></noscript>
            </head>
            <body onload="window.location = 'kernel_hal/index.html'">
              <a href="kernel_hal/index.html">look here</a>
            </body>
          </html>
          EOF
      - name: Deploy to Github Pages
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: target/doc
