[package]
name = "kernel-hal-bare"
version = "0.1.0"
authors = ["Runji Wang <wangrunji0408@163.com>"]
edition = "2018"
description = "Kernel HAL implementation for bare metal environment."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
spin = "0.5"
executor = "0.6.0"
trapframe = "0.1.1"
core = { package = "core-futures-tls", version = "0.1.0" }
kernel-hal = { path = "../kernel-hal" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.8"
uart_16550 = "0.2"
apic = { git = "https://github.com/rcore-os/apic-rs" }

[target.'cfg(any(target_arch = "riscv32", target_arch = "riscv64"))'.dependencies]
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"], rev = "c62af46" }
